DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;

Create TABLE EMPLOYEE
(
ID NUMBER,
NAME VARCHAR2(10),
DESIGNATION VARCHAR(20),
SALARY NUMBER
);

INSERT INTO EMPLOYEE (ID,NAME,DESIGNATION,SALARY)
   VALUES(01,'FATIMA','ENGINEER',70000);

INSERT INTO EMPLOYEE VALUES(02,'CHOMOK','MANAGER',50000); 

INSERT INTO EMPLOYEE VALUES(03,'OMI','DEVELOPER',10000); 

INSERT INTO EMPLOYEE VALUES(04,'NUHA','DEVELOPER',40000);


Create TABLE DEPARTMENT
(
ID1 VARCHAR2(10),
NAME VARCHAR2(10) ,
BRANCH VARCHAR2(10),
EXPERIENCE NUMBER
);

INSERT INTO DEPARTMENT (ID1,NAME,BRANCH,EXPERIENCE)
   VALUES('01A','FATIMA','BANASREE',7);

INSERT INTO DEPARTMENT VALUES('02B','CHOMOK','BANASREE',5); 

INSERT INTO DEPARTMENT VALUES('03C','OMI','AFTABNAGAR',1); 

INSERT INTO DEPARTMENT VALUES('04D','NUHA','NIKETON',4);


COMMIT;

CREATE OR REPLACE VIEW MYVIEW (VIEW_ID, VIEW_NAME, VIEW_DES) AS
SELECT ID, NAME, DESIGNATION
FROM EMPLOYEE ;


Select * from employee;
SELECT * FROM MYVIEW;
